### ISSUE TITLE
Why no save?

### ISSUE THREAD

**Issue by yhyu13** [Vahe1994/SpQR#11]
HI, Thanks for sharing this great quantization technique

But I am not sure I understand why saving is not supported at this moment, in the main.py

```
    if args.save or args.save_safetensors:
        raise NotImplementedError()
```

What are the obstacles that prevent compressed models from being saved/reload?

Do you know any techniques that allow dumping the model VRAM to disk and reload from disk directly?

**Comment by qwopqwop200** [comment]
https://github.com/Vahe1994/SpQR/issues/1

**Comment by qwopqwop200** [comment]
https://github.com/Vahe1994/SpQR/issues/1
