### ISSUE TITLE
How to test inference speed?

### ISSUE THREAD

**Issue by JianbangZ** [Vahe1994/SpQR#12]
Anyway we can test the speedup effect?

**Comment by havietisov** [comment]
I crave for this inference code. 
We crave for this inference code.
EVERYONE crave for this inference code.
Man, please!

**Comment by evolu8** [comment]
Yes, looking forward to this inference code release. 

Do you need any help with it?

**Comment by MeJerry215** [comment]
so where is the inference code? Its about two months.

**Comment by elvircrn** [comment]
Inference code is now available on SpQR-side.

Refer to https://github.com/huggingface/transformers/pull/34976 for huggingface integration.
