### ISSUE TITLE
How evaluation being done without storing quantized weights?

### ISSUE THREAD

**Issue by tahmiddialpad** [Vahe1994/SpQR#24]
I would like to know how the quantized model's performance is evaluated while keeping this [line](https://github.com/Vahe1994/SpQR/blob/e75c55bbc1c96f8411bc58be6d8f44596de44f84/main.py#L236) blank? 

How are the quantized weights being considered while evaluating the performance of the model since the value of quantizers [here](https://github.com/Vahe1994/SpQR/blob/e75c55bbc1c96f8411bc58be6d8f44596de44f84/main.py#L298) is empty?

**Comment by poedator** [comment]
Hello, @tahmiddialpad,

Thank you for interest to SpQR compression. 

When the quantize() function is called in line 217(https://github.com/Vahe1994/SpQR/blob/e75c55bbc1c96f8411bc58be6d8f44596de44f84/main.py#L217) it quantizes and then immediately dequantizes the model weights. See lines 178-189 in spqr_engine.py(https://github.com/Vahe1994/SpQR/blob/e75c55bbc1c96f8411bc58be6d8f44596de44f84/spqr_engine.py#L178-L189). 
The line that you mentioned would return quantizers necessary to save the compressed model. This saving functionality is not yet implemented.

**Comment by poedator** [comment]
Hello, @tahmiddialpad,

Thank you for interest to SpQR compression.

When the quantize() function is called in[ line 217 ](https://github.com/Vahe1994/SpQR/blob/e75c55bbc1c96f8411bc58be6d8f44596de44f84/main.py#L217)it quantizes and then immediately dequantizes the model weights. See [lines 178-189 in spqr_engine.py()](https://github.com/Vahe1994/SpQR/blob/e75c55bbc1c96f8411bc58be6d8f44596de44f84/spqr_engine.py#L178-L189).
The line that you mentioned would return quantizers necessary to save the compressed model. This saving functionality is not yet implemented.
