### ISSUE TITLE
Does permutation order have to be included when saving the quantized model?

### ISSUE THREAD

**Issue by luccareinehr** [Vahe1994/SpQR#31]
I understand model saving is yet to be implemented, but it looks like permutation may increase the memory footprint of the model. 

If we save an SpQR-quantized model in a file and try to dequantize it, we'll end up with a permuted version of the weight matrices (in floating points). So, to use it in inference, it would need to be de-permuted.

Is there any other way of doing inference in SpQR without having to save the permutation order?

**Comment by luccareinehr** [comment]
And I don't see how it'd be possible to save the model de-permuted while in SpQR representation. Permutation is done by columns, while quantization is done by blocks. There is more granularity with permutation. Consequently, the quantizing statistics (scales and zeros) computed for a permuted input matrix do not correspond correctly to the blocks in the unpermuted matrix.

For example, say we use a groupsize of 16. If column 0 is permuted and becomes column 20, the 1st-order scale and zero vectors for this column are also calculated for all other columns 16-31. However, these columns were permuted from other groups of the original matrix - for instance, column 16 may have been column 999 before. So we can't just de-permute all scale vectors, because they correspond to multiple columns...

**Comment by Vahe1994** [comment]
Hello, I'm sorry, for late response.
> I understand model saving is yet to be implemented

Yes you are correct, here is a draft PR of model saving https://github.com/Vahe1994/SpQR/pull/32, it is almost complete,but not tested yet.
>  permutation may increase the memory footprint 

Storing permutation will increase memory footprint by a negligible amount, less than 0.01 bits per parameter.

>If we save an SpQR-quantized model in a file and try to dequantize it, we'll end up with a permuted version of the weight matrices (in floating points). So, to use it in inference, it would need to be de-permuted.

Yes, or you can de-permute activations.

> Is there any other way of doing inference in SpQR without having to save the permutation order?

Unfortunately, we are not aware of it. As a workaround, you can skip permuting the activations, via identity option. Usually, the difference between act_order and identity is not large See Table 3 in [SpQR](https://arxiv.org/pdf/2306.03078.pdf) paper.

![image](https://github.com/Vahe1994/SpQR/assets/4429900/a9c63739-ecf5-48c1-8aae-7cde8f1628c9)

**Comment by luccareinehr** [comment]
No worries about the time. That's awesome, thanks! :)
